version: "3.8"

services:
  # --- OBSERVABILITY STACK START ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Use the path relative to the root of the project
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pred-network # Use the name of the network in the main branch

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - pred-network
  # --- OBSERVABILITY STACK END ---

#Have to be added in main docker-compose.yml file.
